get:
  tags: [ setting ]
  summary: 获取提醒列表
  security:
  - wechat: []
  parameters:
    - name: birthId
      in: query
      type: integer
      required: true
      description: 生日 Id
  responses:
    200:
      description: 设置列表
      schema:
        type: array
        items:
          $ref: "#/definitions/Setting"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
post:
  tags: [ setting ]
  summary: 新增提醒
  security:
  - wechat: []
  parameters:
    - name: birthId
      in: formData
      type: integer
      required: true
      description: 生日 Id
    - name: advance
      in: formData
      type: integer
      minimum: 0
      required: true
      description: 当前/提前提醒的天数
    - name: time
      in: formData
      type: string
      required: true
      description: 提醒的时间
  responses:
    201:
      description: 生日
      schema:
        $ref: "#/definitions/Setting"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
put:
  tags: [ setting ]
  summary: 修改提醒
  security:
  - wechat: []
  parameters:
    - name: settingId
      in: formData
      type: integer
      required: true
      description: 提醒 Id
    - name: advance
      in: formData
      type: integer
      required: false
      minimum: 0
      description: 当前/提前提醒的天数
    - name: time
      in: formData
      type: string
      required: false
      description: 提醒的时间
  responses:
    200:
      description: 生日
      schema:
        $ref: "#/definitions/Setting"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
delete:
  tags: [ setting ]
  summary: 删除提醒
  security:
  - wechat: []
  parameters:
    - name: settingId
      in: query
      type: integer
      required: true
      description: 设置 Id
  responses:
    200:
      description: 删除完成
      schema:
        $ref: "#/definitions/SuccessResponse"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
