swagger: "2.0"
info:
  version:
  title: 生日提醒
# during dev, should point to your local machine
host:
# basePath prefixes all resource paths
basePath: /api
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - text/xml
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
  - name: birth
    description: 生日
  - name: setting
    description: 提醒
  - name: wechat
    description: 微信
securityDefinitions:
  oauth:
    type: apiKey
    name: cookie
    in: header
    description: 使用 Wechat OAuth 2.0 进行登陆，登陆后会设置 session，后续请求带上 session 即可
